lst = ['abc', 'cde', 'efg', '1', '2', '6']
lst2 = ['extend', 'lst2']
print(f'list "lst" : \n{lst}')
print(f'list "lst2" : \n{lst2}')
print('---------------------------------------------')
# list.append()
lst.append('xyz')
print(f'list "lst" after append "xyz" : \n{lst}')
# list.insert()
lst.insert(0,'insert')
print(f'list "lst" after insert "insert" at 1st place in list: \n{lst}')
# list.extend()
lst.extend(lst2)
print(f'list "lst" after extend list "lst2": \n{lst}')
# list.index()
print(f'Index of element "efg" in list "lst": \n{lst.index("efg")}')
# list.remove()
lst.remove("abc")
print(f'list "lst" after remove element "abc" : \n{lst}')
# list.sort()
lst.sort()
print(f'list "lst" after sort : \n{lst}')
# list.reverse()
lst.reverse()
print(f'list "lst" after reverse : \n{lst}')
# list.pop()
lst.pop(0)
print(f'list "lst" after remove first element : \n{lst}')
print(f'the return of lst.pop(2): \n{lst.pop(2)}')
print(f'list "lst" after lst.pop(2) : \n{lst}')
